global using ByReplace.Analyzers;
global using ByReplace.Commands.Apply.Parameters;
global using ByReplace.Commands.Apply.Rule;
global using ByReplace.Commands.Logo;
global using ByReplace.Commands.Version;
global using ByReplace.Exceptions;
global using ByReplace.Mappers;
global using ByReplace.Matches;
global using ByReplace.Models;
global using Cocona;
global using Microsoft.Extensions.DependencyInjection;
global using MoreLinq.Extensions;
global using NuGet.Protocol;
global using NuGet.Protocol.Core.Types;
global using NuGet.Versioning;
global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Text.Json;
global using Konsole;
global using static ByReplace.Mappers.DirectoryThree;
global using ByReplace.Printers;
global using ByReplace.Printers;
global using static ByReplace.Mappers.DirectoryThree;
global using ByReplace.Commands.Command;
